###
GET http://localhost:8000/test

###
GET http://localhost:8000/test/benny

###
POST http://localhost:8000/caesar
Content-Type: application/json

{
  "text": "welcome kodkod",
  "offset": 16,
  "mode": "encrypt"
}

###
POST http://localhost:8000/caesar
Content-Type: application/json

{
  "text": "mubsecu aetaet",
  "offset": 16,
  "mode": "decrypt”"
}
###
GET http://localhost:8000/fence/encrypt?text=welcome%20kodkod
###
POST http://localhost:8000/fence/decrypt
Content-Type: application/json

{
  "text": "wloeokdecmkdo"
}